#language: rust
install: false
sudo: false

services:
  - docker

before_install:
- docker pull teaclave/teaclave-build-ubuntu-1804-sgx-2.9.1
- docker run -it -v $PWD:/teaclave -w /teaclave teaclave/teaclave-build-ubuntu-1804-sgx-2.9.1 \
          export PATH=$PATH:/root/.cargo/bin; \
          /bin/bash -c "source /opt/sgxsdk/environment;  \
          mkdir build && cd build; \
          cmake -DSGX_SIM_MODE=ON -DTEST_MODE=ON .. && make; \
          make sgx-test"

script:
  #- diff -u <(echo -n) <(rustfmt -d $(find . -type f -name '*.rs' -not -path "./vendor/*"))
  - echo "done"

after_success:
  - bash <(curl -s https://codecov.io/bash)  -y .github/codecov.yml

cache:
  directories:
    - .cache
